gitGraph
  commit id: "Инициализация проекта"
  commit id: "Создание базовой архитектуры приложения" tag: "v0.1.0"
  commit id: "Реализация функционала поиска и отображения курсов"
  commit id: "Добавление возможности записи на курсы" tag: "v0.2.0"
  commit id: "Интеграция платёжного шлюза"
  commit id: "Реализация функционала прохождения уроков"
  commit id: "Отображение прогресса пользователей" tag: "RC_1.0"
  commit id: "Подготовка первого релиза" tag: "v1.0.0"
  commit id: "Добавление уведомлений для студентов"
  commit id: "Реализация функционала генерации сертификатов"
  commit id: "Добавление системы аналитики"
  commit id: "Улучшение производительности" tag: "RC_2.0"
  commit id: "Релиз системы" type: HIGHLIGHT tag: "v1.1.0"
