mindmap
  root(Платформа Курсы иностранных языков)
    Авторизация и регистрация
      Регистрация
      Вход
      Восстановление пароля
    Обучение
      Запись на курс
      Просмотр курсов
      Просмотр прогресса
      Прохождение тестов
    Онлайн-встречи
      Интерактивные занятия
      Записи занятий
      Задания
    Уведомления
      Напоминания о курсах
      Новые предложения
      Уведомления о фидбэке
    Профиль пользователя
      Просмотр профиля
      Редактирование профиля
    Администрирование
      Управление пользователями
      Создание и редактирование курсов
      Обработка отзывов
    Аналитика
      Отслеживание прогресса пользователей
      Генерация отчётов
      Мониторинг вовлечённости
      Сбор статистики
