quadrantChart
    title Development Priorities
    x-axis Low Priority --> High Priority
    y-axis Low Complexity --> High Complexity
    quadrant-1 High Priority
    quadrant-2 Requires Analysis
    quadrant-3 Re-evaluate
    quadrant-4 Can Be Improved
    Authorization and Registration: [0.2, 0.8]
    Course Search: [0.68, 0.1]
    Course Enrollment: [0.8, 0.65]
    Payment Processing: [0.7, 0.8]
    Lesson Completion: [0.8, 0.3]
    Progress Tracking and Analytics: [0.8, 0.56]
    Certificate Generation: [0.7, 0.4]
    Notifications: [0.3, 0.7]
    Custom Themes: [0.2, 0.2]
    Favorite Courses: [0.35, 0.15]
